### ISSUE TITLE
Additional Unit of Pressure - mmHg (millimeters of mercury) for blood pressure?

### ISSUE THREAD

**Issue by james1301** [anjdreas/UnitsNet#151]
Hi there,

I am wanting mmHG for blood pressure but it is not currently in your units system. I am a bit confused what I would actually have to do to add this as a custom unit? I believe it should be added to the PressureUnit but I don't know the best way to go about this. I've looked at your documentation but I'm no clearer on what the process would actually be. My software is medically orientated so there may be other ones like this.I would like to continue to use your NuGet package.

Thanks,
James

**Comment by eriove** [comment]
I would suggest that you [create a fork](https://help.github.com/articles/fork-a-repo/) and add the unit `MillimeterOfMercury` in [Pressure.json](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/Scripts/UnitDefinitions/Pressure.json). Once you've done that you can [create a pull request](https://help.github.com/articles/creating-a-pull-request/) and @anjdreas can review the pull request and merge it.

**Comment by anjdreas** [comment]
@eriove :+1: 

@james1301 
Did you read this? https://github.com/anjdreas/UnitsNet/wiki/Adding-a-New-Unit
Don't hesitate to ask if the instructions are unclear. The article assumes you are familiar with C# .NET and JSON.

**Comment by james1301** [comment]
Thank you guys. I had read that yes @anjdreas, but was unsure if this should actually go into your main project. As I was potentially adding medically relevant units, I was wondering what the best way to add custom units were to just my system. I may look at this in future as it is a little more work than I was thinking at this point in my project. I will also think about using the Torr value, thanks @eriove .

**Comment by anjdreas** [comment]
@james1301 You could write your own `PressureExtensions` class with extension methods `FromMilimeterOfMercury()` to construct and `MilimetersOfMercury()` to convert to this unit.
`Parse()`, `As()` and `ToString()` and probably some other methods will still not recognize your custom unit since there is no PressureUnit enum value for it.

That said, I don't think this belongs in `Pressure`, but rather in `BloodPressure` under a medical purpose nuget, just as you suggested yourself. I am entirely open to this, but I don't personally have enough time or interest to pursue that myself. If you want to go that direction, let me know and I will assist you in any way I can.

I'm closing this issue for now.
