### ISSUE TITLE
Light

### ISSUE THREAD

**Issue by jbienzms** [anjdreas/UnitsNet#165]
One thing I realized today that I was surprised to find: it appears UnitsNet doesn't seem to have a unit of measure for light? I expected to see something that would deal with Lux, Lumen, Candels, etc. Did this unit of measure just never come up before or am I asking a silly question? I ask because I was thinking about using such a unit to create a new sensor type (LightSensor). I'd love to hear your thoughts.

Obviously this is not an issue but an enhancement.

Thanks!

**Comment by anjdreas** [comment]
I suppose it just never came up :-) Most of the units added so far have been due to someone needing that particular unit or class of units.

Should be fairly easy to add though, you are welcome to give it a go if you like. It's mostly about adding a new .json file, regenerating the code and filling out test values for the generated tests. All steps are listed here: https://github.com/anjdreas/UnitsNet/wiki/Adding-a-New-Unit

I suppose for your case, we are talking illuminance as the amount of light hitting the sensor surface? I'm not light unit expert, so correct me if wrong :-)

If so, it would be about adding Illuminance.json based on https://en.wikipedia.org/wiki/Illuminance

And this table shows a bunch of relevant measures:
https://en.wikipedia.org/wiki/Illuminance#External_links

I can help out, but I do have limited time these days. A baby in the house and just moved to a new location keeps me quite busy after work hours :-)

**Comment by anjdreas** [comment]
Do you still plan to do anything here?

**Comment by anjdreas** [comment]
Just following up old issues, do you want to do anything here or should I close this for now?

**Comment by jbienzms** [comment]
You can close it. Thank you. Some day I will push a package update on my end. For now it's there in source. I need to, I have other bugs to address. Just never get to it.

________________________________

**Comment by anjdreas** [comment]
Alright, no problem. Just reopen this whenever it is convenient.
