### ISSUE TITLE
Normal flow rate Nm³/h

### ISSUE THREAD

**Issue by MarcDrexler** [anjdreas/UnitsNet#212]
There are already units for flow rate implemented, however we need to convert m³/h to Nm³/h.
This is used to denote gas volumes at normalized conditions.
**Flow rate** would be the correct unit class to add this unit, am I correct?

**Comment by eriove** [comment]
Some quick googling suggests that the "normal" temperature varies from application to application (or industry to industry). Wouldn't that mean the conversion rate isn't constant?

**Comment by MarcDrexler** [comment]
Yes, the temperature is important. But there are standards for this as well:
DIN 1343:  273,15 K = 0 °C
ISO 2533: 288,15 K = 15 °C
ISO 6358 / ISO 8778 (standard reference atmosphere): 293,15 K = 20 °C
Like you said, depending on the application/industry, different temperatures will be used. But these temperatures are still constant.
Do you think there is a chance to include this in UnitsNet somehow? 
If I know where, I would try to contribute this one, instead of implementing the conversion in my own application.

**Comment by anjdreas** [comment]
I am not familiar with this unit, but from my googling it seems there are "normal" vs "standard" flow rates.
http://control.com/thread/1026177675

> The difference between normal and standard conditions is the temperature. Here is an explanation that I found.
The most common units of industrial gas measurement are; SCFH and Nm3/hr. Note, that there is a difference between Normal cubic meters and Standard cubic meters. The difference lies in the reference temperature that each specific unit is measured with respect to. Normal meters are measured with respect to the Metric system (0C, 1 atm), and standard meters are measured with respect to the imperial system of standard conditions (70F, 1atm).
1 Normal Cubic Meter equals 38.042 SCF
There are also other defined "standard" conditions at other temperatures (32F, 60F), but normal is always 0C.

Then another guy goes:
> The values used for "Normal" & "Standard" conditions vary by country and industry. Some places they are the same others quite different. In this country 60, 68, 70, and 75 F are used depending on the industry as are 14.696, 14.7, 14.73 psiA. The most common that I see are;
Standard: 70 F & 14.696 psiA (21 C & 1 Atm)
Normal: 32 F & 14.5038 psiA (0 C & 1 Bar) or, 32 F & 14.696 psiA (0 C & 1 Atm)

So my understanding is, when representing flow rate of gases, you need to consider the temperature to get the right volumes. Nm3/h and Sm3/h is used to denote Normal and Standard flow rates, but the definitions of these vary between applications and industries.

If I am not entirely mistaken, we can't convert from FlowRate [m3/h] to normal/standard flow rates [Nm3/h and Sm3/h], because that would be converting X liters/hour of gas with no known reference temperature to Y liters/hour of gas with a certain reference temperature. There is missing information in FlowRate as it is today.

I believe we need a custom handwritten type for this, something like `FlowRateAtTemperature`, that holds two properties: `FlowRate FlowRate { get; }` and `Temperature Temperature { get; }`
Then it has a constructor to set those readonly properties, and constructor methods like `FromDin1343(FlowRate flowRate) {}` and `FromIso2533(FlowRate flowRate) {}` that calls the constructor with the correct reference temperature.

It can then have conversion property getters like `Din1343 => /* conversion from FlowRate and Temperature to Din1343 /*;`

You can then convert that from m3/h to mm3/h and all the other FlowRate units already defined, by calling:
```csharp
var iso2533 = FlowRateByTemperature.FromIso2533(FlowRate.FromCubicmetersPerHour(1));
double mm3phIso2533 = iso2533.FlowRate.CubicmillimetersPerHour;
FlowRateByTemperature din1343 = iso2533.Din1343;
double mm3phDin1343 = din1343.CubicmillimetersPerHour;
```

Another approach would be to have types like `FlowRateDin1343` and `FlowRateIso2533` with only a `FlowRate` property, and conversion properties to the other flow rate types.

The same example would be:
```csharp
var iso2533 = new FlowRateIso2533(FlowRate.FromCubicmetersPerHour(1));
double mm3phIso2533 = iso2533.FlowRate.CubicmillimetersPerHour;
FlowRateDin1343 din1343 = iso2533.Din1343;
double mm3phDin1343 = din1343.CubicmillimetersPerHour;
```

Does that make sense?

Now, we are talking gases here, but I believe liquids like water also have a tiny bit of thermal expansion. Do we want to simply represent the flow rate at a certain temperature or do we also want to convert from one temperature to another? If so, how do we distinguish between the conversion for different gases and liquids?

**Comment by MarcDrexler** [comment]
Thank you very much for your investigation!
Today I only have the requirement to work with gases but others will follow (co2 emission, mol).
I really cannot tell you which benefits (advantages) these approaches offer in detail and which one feels right. But I'm sure the approach we decide for will always be wrong 😃

**Comment by anjdreas** [comment]
That's.. troubling :-)

I really need a domain expert to recommend a solution here, someone who know what conversions are used and how UnitsNet would best help out in representing and converting between units of standard flow rates and standard volumes. 

I can help out with how to fit this best into UnitsNet, but I am not in a good position to decide how we best go about implementing this.

I found this conversion tool:
https://www.almig.com/tools/standard-cubic-metres.html#

Apparently there are a number of variables to go into calculating the standard volume from a DIN1343 or ISO2533 normal volume, such as humidity, air pressure and temperature.

**Comment by anjdreas** [comment]
How do we move this forward?

**Comment by anjdreas** [comment]
Anyone care to move this forward? Or else I will close this due to inactivity.

**Comment by anjdreas** [comment]
Actually, closing this. Reopen if you intend to pursue this.
