### ISSUE TITLE
Which of these units would be suitable for inclusion into UnitsNet?

### ISSUE THREAD

**Issue by cumminsjp** [anjdreas/UnitsNet#240]
I am at the beginning of year-long agriculture project where I have to deal with various measurements that use units not currently in UnitsNet.  I am currently evaluating whether it is suitable (either partially or entirely) to include these and actually perform the work and provide it back for inclusion in UnitsNet.  I had started this on another project, but didn't follow through (but would complete those changes as part of this  project).

Here is what I need.   And I know many of these have variants, so they would like resolve to multiple units of measure (or resolve to a "statistical" unit of measurement for conversion).

cwt - mass -  https://en.wikipedia.org/wiki/Hundredweight (Snap Beans unit of measure)
bushel - volume - https://en.wikipedia.org/wiki/Dry_measure
bale - mass -  http://www.convertunits.com/from/lbs/to/bale+[US]
animal unit - mass - https://en.wikipedia.org/wiki/Animal_unit

lbs/bales - ?? (_makes no sense to me...waiting for clarification_).

lbm/ac - area density - Pounds per acre. (already done in a branch for the *** project feature/add-areadensity. 

discrete count  / quantity - (used for christmas tree yields).
**Is there an existing unit for discrete counts?  Would I use a RatioUnit.DecimalFraction of 1?**

g/L - Mass concentration - grams per Liter

I would like to open this for discussion.  And soon I'd like to have a rough idea of what I potentially could provide back to UnitsNet and what could (or should not) be included, since it may impact our scheduling of work for the project.

Thanks!

**Comment by anjdreas** [comment]
Hi, let me see if I can address your points:

### cwt - mass
This seems well defined and straight forward to add to Mass.

### bushel - volume
This seems well defined and straight forward to add to Volume.

### bale - mass
This sounds like it has a number of variations:
http://www.businessdictionary.com/definition/bale.html

Your link says 1 bale = 480 pounds, but my link says 
> Standard bale weighs 500 pounds (226.8 kilograms) gross or 478 pounds (216.8 kilograms) net.
What values and namings would you use here?

### animal unit - mass
This unit seems less well defined. The wiki says:
> The term has been variously defined by regulation in different jurisdictions, and by livestock management specialists, rangeland resource managers and others. Consequently, when using or interpreting the term, care is needed to ensure that a definition appropriate for the purpose is being used.

What values and namings would you use?

### lbs/bales
Awaiting more info here. My understanding is that a "bale" in some contexts is just a bundle, so this would define how many pounds per bundle. If so, that seems more application specific than a UnitsNet candiate, as you are working with pounds (mass) and I assume you will use these values for arithmetic rather than unit conversions.

### lbm/ac - area density
AreaDensity, new to me, but seems generic enough to be a candidate for UnitsNet.
https://en.wikipedia.org/wiki/Area_density

### discrete count / quantity
Why would you want this? Why is not `int`, `double` or `decimal` types sufficient? I don't immediately see what kind of conversions you can do with this type. You could use `Ratio` type, but its semantics are ratios, not counting. It exists, because it makes sense to convert between the different ratio representations.

### g/L - Mass concentration - grams per Liter
See [Density](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/UnitDefinitions/Density.json)

Hope this helps!

**Comment by Yannick-Rondeau** [comment]
Hey @cumminsjp! I would be very happy if Units.Net would include that `cwt` unit! I know it's pretty simple to retrieve since you just divide the pounds, but in some cases it could be way easier to get a value using a `Mass.HundredWeight`!

Let me know if you ever implement that, I would love to include that in mine too.

**Comment by cumminsjp** [comment]
lbs/bales - was a unit in an existing application.  But I think it may be a mistake.

bale - in my case, I'm dealing with cotton (which is in your link definition).  But even that varies between country.  Brazil, Egypt/UK, BangladeshIndiakistan, and the US.  Probably not a UnitsNet candidate unless we add/qualify them all.

discrete count / quantity - makes sense.  I wanted to identify a particular crop yield as something in the data model.  But there are no conversions involved. 

animal unit - mass - I need the 1000 lb version (the US Natural Resources Conservation Service definition which is used for comparing manure nitrogen and phosphorus).  Is there a way to work that into UnitsNet or shall I leave that out?

Thanks for advice!

**Comment by anjdreas** [comment]
> animal unit - mass - I need the 1000 lb version

Well.. I haven't thought this through, but somehow the wording "animal unit" seems very application specific to me, and may better be defined in the application. So I would probably recommend you create that type/unit in the app, then use `Mass` where appropriate for any conversions or calculations, if that makes sense.

**Comment by anjdreas** [comment]
Any progress here?

**Comment by cumminsjp** [comment]
The Cwt unit already went (I did early because I had never contributed code on Git and wanted to work through mechanics).  My project runs until December (so we are really just getting started).  Although any PRs I would have, I'd probably have in my the end of June. 

But I'm in agreement with your comments (in fact, they've gotten a bit more complicated on the application side).  

But feel free to close this issue.
