### ISSUE TITLE
Parsing feet and inches ignores inches in results

### ISSUE THREAD

**Issue by baylesj** [anjdreas/UnitsNet#72]
Code to replicate:

```c#
string length = "60 ft 1 in";
Length l = Length.Parse(length);
string s = l.FeetInches.ToString();
```
l.Feet is now 60 instead of the actual value of 60.0833333333

s is "60 ft 0 in" instead of being equal to length.

**Comment by anjdreas** [comment]
Thanks, this was recently introduced in #69.

@mperdeck would you care to take a look?

**Comment by anjdreas** [comment]
#64 is probably involved too by @maherkassim .

I can take a look this weekend if no one addresses it before then.

**Comment by maherkassim** [comment]
Ahh yes, this is definitely a result of the parsing because anything after the initial number will be treated as part of the unit. The current parsing method was geared more towards use with strings in the format "<value> <unit>" and will need to be extended to consider these cases for imperial units. I imagine we may eventually want to parse other variations such as 60' 1" = 60ft 1in.

I am currently travelling this week so it will be difficult to look into the specifics.

**Comment by mperdeck** [comment]
When I created FeetInches, I didn't do the parsing bit. I guess that "60 ft 1 in" is parsed as "60 ft" by the generated parsing code. This generated code seems to assume that input strings are always a single number followed by a unit, and never 2 number/unit pairs.

I didn't do the parsing, because 1) making it work seemed very complicated, 2) the most common use case for feet/inch combinations is for body weight in the UK and US, and I expected that the feet and inches would in most cases be collected separately - such as a form that has separate input fields for feet and inches.

**Comment by baylesj** [comment]
@maherkassim Funnily enough that variation you mention is exactly what I am trying to do.

I'm developing a MVC site for a wood products company and need to parse user inputs including (in brackets due to confusing use of quotes):
```
<60>, <60'>, <60' 1">, and <60' 1 1/2">
```
I am currently catching the compound case in a seperate regex, but am willing to look at improving the parser in this library if it doesn't get inertia.

Thanks for looking into this!

**Comment by anjdreas** [comment]
I've done something similar in a side project using regex to parse "3 1/2", "1/4", "½", "¾" along with a unit and an item description for recipe parsing. I'll just throw it in here for your reference. I don't know how good of a approach it is, but it was working. I think one of the things I did was string.Replace() on those "½" strings to "1/2" equivalent strings as a pre-process step, so the input would match the patterns in the examples below.

```
// Examples: "1 L milk" and "1 1/2 L milk"
// The abbreveations in this list are units for cooking, such as L for liter etc.
string pipedAbbreviations = string.Join("|", _cookingUnitAbbreviations);
string regex = @"(?<numeral>(?<decimalNumeral>{{decimalRegex}})|(?<fractionNumeral>{{fractionalRegex}})|(?<integerNumeral>\d+))\s{0,1}(?<unitAbbrev>{{pipedUnitAbbrevs}}){0,1}\s+(?<desc>.*?)$"
    .Replace("{{pipedUnitAbbrevs}}", pipedAbbreviations)
    .Replace("{{decimalRegex}}", @"\d+[\.|,]\d+")
    .Replace("{{fractionalRegex}}", @"(?:(?<wholeNumber>\d+)\s+){0,1}(?<fraction>(?<numerator>\d)+\s{0,1}/\s{0,1}(?<denominator>\d+))");
```

**Comment by anjdreas** [comment]
Anyone taking a stab at this?

**Comment by maherkassim** [comment]
Yup, sorry about the delay. In #81 I've created an initial attempt at improving the parsing that will at least multi-quantity strings like 6ft 1in. Let me know if you think we should take a different approach.

**Comment by maherkassim** [comment]
Note: this does not yet address the issue of parsing input with fractions.

**Comment by anjdreas** [comment]
This is fixed now. Tested in LinqPad with nuget 3.33:
```
string length = "60 ft 1 in";
Length l = Length.Parse(length);
Console.WriteLine(l.FeetInches.ToString());

// Result: 60 ft 1 in
```

**Comment by danny-boy-online** [comment]
I copy-pasted the above and it seems to fail -- I am using latest UnitsNet nuget 4.97.1

![image](https://user-images.githubusercontent.com/48072753/125779527-6105944e-0de9-413f-9884-ba1701cfc8bb.png)

Is this a bug or am I using a deprecated approach as i can see this thread is from 2016 ?!!

**Comment by angularsen** [comment]
The parsing became complicated, so we decided to move it to a separate method.

`Length.ParseFeetInches("60 ft 1 in")`
https://dotnetfiddle.net/duQg38

**Comment by angularsen** [comment]
Someone posted a question and later seems to have deleted it, so for future reference:

The parsing became complicated, so we decided to move it to a separate method.

`Length.ParseFeetInches("60 ft 1 in")`
