### ISSUE TITLE
Represent rate of change more generically

### ISSUE THREAD

**Issue by anjdreas** [anjdreas/UnitsNet#89]
Similar to discussion on dimensions in #73, I speculate if there is a need for a more generic way of expressing rate of change for any type of unit. Currently we have the following rate of change units:

Flow (volume over time)
Speed (distance change over time)
Acceleration (speed change over time)
RotationalSpeed (angle change over time)

In #88 there are some further suggestions to units, such as 
PressureChangeRate (pressure change over time)
RotationalSpeedChangeRate (angular speed change over time)
ValveDriveSpeed (fraction change over time)

**Comment by eriove** [comment]
Not sure if I should put this in it's own issue...

Have you considered operator overloading to convert between different units (i.e. dividing with a `Speed` with a `TimeSpan` should return an acceleration)? It opens up a large amount of new work with with defining all the different relations but it would give you compile time dimensional analysis.

**Comment by InitialForce-TeamCity** [comment]
I have not personally considered operator overloading so far, mostly because I have simply not had the need for my own purposes, but I'm leaning towards *why not*? I don't see this easily automated with the code generation powershell scripts though, but all generated unit classes are partial so adding operator overloads to say `Custom Code\Length.extra.cs` should be straight forward.

If you want to take a stab at this, please feel free to start a PR to move that discussion there and start implementing some typical usecases.

**Comment by anjdreas** [comment]
I have not personally considered operator overloading so far, mostly because I have simply not had the need for my own purposes, but I'm leaning towards why not? I don't see this easily automated with the code generation powershell scripts though, but all generated unit classes are partial so adding operator overloads to say Custom Code\Length.extra.cs should be straight forward.

If you want to take a stab at this, please feel free to start a PR to move that discussion there and start implementing some typical usecases.

**Comment by anjdreas** [comment]
I still think this issue of representing rate of change in a generic way has value in its own, so I'm leaving this open.

**Comment by anjdreas** [comment]
Closing this as I don't really have a good plan here, and no intention to follow up on it myself.
