### ISSUE TITLE
Json.NET conversion

### ISSUE THREAD

**Issue by neutmute** [anjdreas/UnitsNet#92]
Hello - I tried persisting the `Area` type with Newtonsoft's Json.NET but by default it makes a big nested object with all the internal types like this 

	{
		SquareCentimeters: 200000.0,
		SquareDecimeters: 2000.0,
		SquareFeet: 215.27830102364831,
		SquareInches: 31000.062000124002,
		SquareKilometers: 2E-05,
		SquareMeters: 20.0,
		SquareMiles: 7.7220077220077222E-06,
		SquareMillimeters: 20000000.0,
		SquareYards: 23.919811224849816
	}

when what I need is just the simple m^2 value of 20.0 (Neo4j database can't persist the nested object).

I wrote a custom converter and it works nicely
https://github.com/neutmute/Neo4jClient.Extension/blob/cskardon-T-3/Neo4jClient.Extension.Test/CustomConverters/AreaJsonConverter.cs

This looks like it could be generated with some magical powershell scripts.
I'm not sure if my problem is an edge case or of wider value.

Would you consider a PR with an extra project added: `UnitsNet.JsonConverters` say?

**Comment by neutmute** [comment]
Actually now I'm wondering if this could be done by a single `UnitJsonConverter<T>` that takes an expression tree as a parameter. Users could configure it at app startup to customise persistence to their needs. It would be a separate project with only one class though it that idea works (to avoid introducing Json.NET dependency into main)

**Comment by anjdreas** [comment]
From the start I did not want to take on serialization. There are so many pitfalls and easy to make breaking changes, so I felt safer leaving this up to client code. I'm open to discuss a solution here though, as I'm sure many will stumble across the same problem.

The most robust method would be to serialize both value and unit, so that in case the default/base unit changes at any point, we have a better chance of still parsing it. Unit abbreviations like "m" and "kg" are pretty fixed, but can be ambiguous. For instance, several Ratio units have no abbreviation. Unit enum names are unique, but it is hard to guarantee they will never be renamed. So I'm not sure what would be a good choice for serializing the unit.

We could add a JsonConverter, but as you say, I would not want to introduce a nuget dependency. With the approach in your second comment, we still would introduce that dependency, won't we? By inheriting from JsonConverter.

**Comment by neutmute** [comment]
Agree on all points and the answer turned out to be quite easy. Using a generic, I define my own converter like this:

    public class AreaJsonConverter : UnitsNetJsonConverter<Area>
    {
        public AreaJsonConverter()
        {
            Init(area => area.SquareMeters, d => Area.FromSquareMeters(d));
        }
    }

It doesn't serialise the base unit since the ctor allows the user to control which unit they want to use - it serializes and deserializes from a simple float/int. This works nicely for MVC model binding too - allowing the binding to come from an `input type=text`:

The `UnitsNetJsonConverter<T>` implementation is a little too big for a post in a stack overflow. I could make a gist, but it would be nice to have a working demo.

How about a PR that creates a folder ~\UnitsNet.Tests\Serialization.Example with some sample code , the `UnitsNetJsonConverter<T>` implementation and unit tests to show it works. That way bug fixes can be contributed more easily than say a gist?

Of course this adds a Json.NET dependency but only to the unit test project.

**Comment by anjdreas** [comment]
I like that, I vote we create an Examples folder at the root, to host any number of example project subfolders such as this one.  If you could also add a section near the bottom of the README.md with info about serialization and link to this example, that would be great.

**Comment by neutmute** [comment]
cool - will do
