### ISSUE TITLE
UnitsNet.2013.sln, UnitsNet.2015.sln

### ISSUE THREAD

**Issue by neutmute** [anjdreas/UnitsNet#94]
Are `UnitsNet.2013.sln`, `UnitsNet.2015.sln` really necessary?
VS 2013 can open VS 2015 projects. 
Having the two solutions means keeping them in sync.
I'd suggest 
 * deleting `UnitsNet.2013.sln` 
 * renaming `UnitsNet.2015.sln` to `UnitsNet.sln`

thoughts?

**Comment by neutmute** [comment]
actually there could be some magic going on here I don't fully get. there is probably a good reason.

**Comment by anjdreas** [comment]
To be honest, I mostly did it because I see a lot of other open source projects do. The only thing I've noticed myself is that VS tends to place its own version number in the solution file whenever it makes changes to it. I'm fine either way, I don't expect to add many projects to this solution so maintenance is fairly low. Unless anyone makes a compelling reason to delete it, I'm just keeping it for now.
